[package]
name = "torrentox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5"
serde = "1.0.210"
serde_bencode = "0.2.4"
serde_derive = "1.0.210"


